/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.lenguaje.universidad.vistas;

import javax.swing.JInternalFrame;

/**
 *
 * @author 
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private JInternalFrame ventanaActual;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnEstudiante = new javax.swing.JButton();
        btnDocente = new javax.swing.JButton();
        btnAsignatura = new javax.swing.JButton();
        btnCurso = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnVerRegistros = new javax.swing.JButton();
        btnVerCurso = new javax.swing.JButton();
        btnCalificacion = new javax.swing.JButton();
        btnVerCalificacion = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        panelInterno = new co.edu.eam.lenguaje.universidad.vistas.PanelInterno();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miEstudiante = new javax.swing.JMenuItem();
        miRegistro = new javax.swing.JMenuItem();
        miVerRegistro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miDocente = new javax.swing.JMenuItem();
        miCalificacion = new javax.swing.JMenuItem();
        miVerCalificacion = new javax.swing.JMenuItem();
        miNota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAsignatura = new javax.swing.JMenuItem();
        miCurso = new javax.swing.JMenuItem();
        miVerCurso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(653, 730));

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tareas"));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/student.png"))); // NOI18N
        btnEstudiante.setToolTipText("Gestión Estudiante");
        btnEstudiante.setFocusable(false);
        btnEstudiante.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEstudiante.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEstudiante);

        btnDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/teacher.png"))); // NOI18N
        btnDocente.setToolTipText("Gestión Docente");
        btnDocente.setFocusable(false);
        btnDocente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDocente);

        btnAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/subject.png"))); // NOI18N
        btnAsignatura.setToolTipText("Gestión Asignatura");
        btnAsignatura.setFocusable(false);
        btnAsignatura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAsignatura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignaturaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAsignatura);

        btnCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/course.png"))); // NOI18N
        btnCurso.setToolTipText("Gestión Cursos");
        btnCurso.setFocusable(false);
        btnCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCurso);

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/registro.png"))); // NOI18N
        btnRegistro.setToolTipText("Crear Registros");
        btnRegistro.setFocusable(false);
        btnRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistro);

        btnVerRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/searchregistry.png"))); // NOI18N
        btnVerRegistros.setToolTipText("Ver Registros");
        btnVerRegistros.setFocusable(false);
        btnVerRegistros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerRegistros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerRegistrosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerRegistros);

        btnVerCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/group.png"))); // NOI18N
        btnVerCurso.setToolTipText("Ver Curso");
        btnVerCurso.setFocusable(false);
        btnVerCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerCurso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCursoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerCurso);

        btnCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/cal.png"))); // NOI18N
        btnCalificacion.setToolTipText("Gestión Calificaciones");
        btnCalificacion.setFocusable(false);
        btnCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCalificacion);

        btnVerCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/grade.png"))); // NOI18N
        btnVerCalificacion.setToolTipText("Ver Calificaciones");
        btnVerCalificacion.setFocusable(false);
        btnVerCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerCalificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCalificacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerCalificacion);

        btnNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/cual.png"))); // NOI18N
        btnNota.setToolTipText("Crear Nota");
        btnNota.setFocusable(false);
        btnNota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNota.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNota);

        jMenu1.setText("Estudiante");

        miEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/student.png"))); // NOI18N
        miEstudiante.setText("Gestión Estudiante");
        miEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEstudianteActionPerformed(evt);
            }
        });
        jMenu1.add(miEstudiante);

        miRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/registro.png"))); // NOI18N
        miRegistro.setText("Registrar Asignatura");
        miRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(miRegistro);

        miVerRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/searchregistry.png"))); // NOI18N
        miVerRegistro.setText("Ver Registros");
        miVerRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(miVerRegistro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Docente");

        miDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/teacher.png"))); // NOI18N
        miDocente.setText("Gestionar Docente");
        miDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDocenteActionPerformed(evt);
            }
        });
        jMenu2.add(miDocente);

        miCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/cal.png"))); // NOI18N
        miCalificacion.setText("Gestionar Calificación");
        miCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalificacionActionPerformed(evt);
            }
        });
        jMenu2.add(miCalificacion);

        miVerCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/grade.png"))); // NOI18N
        miVerCalificacion.setText("Ver Calificaciones");
        miVerCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerCalificacionActionPerformed(evt);
            }
        });
        jMenu2.add(miVerCalificacion);

        miNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/cual.png"))); // NOI18N
        miNota.setText("Crear Nota");
        miNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNotaActionPerformed(evt);
            }
        });
        jMenu2.add(miNota);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Curso");

        miAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/subject.png"))); // NOI18N
        miAsignatura.setText("Gestión Asignatura");
        miAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAsignaturaActionPerformed(evt);
            }
        });
        jMenu3.add(miAsignatura);

        miCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/course.png"))); // NOI18N
        miCurso.setText("Gestión Cursos");
        miCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCursoActionPerformed(evt);
            }
        });
        jMenu3.add(miCurso);

        miVerCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/group.png"))); // NOI18N
        miVerCurso.setText("Ver Curso");
        miVerCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVerCursoActionPerformed(evt);
            }
        });
        jMenu3.add(miVerCurso);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
            .addComponent(panelInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInterno, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaAdminEstudiante();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaAdminEstudiante();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaAdminDocente();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaAdminDocente();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnDocenteActionPerformed

    private void btnAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignaturaActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaAdminAsignatura();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaAdminAsignatura();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnAsignaturaActionPerformed

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaAdminCurso();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaAdminCurso();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnCursoActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaRegistrarCurso();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaRegistrarCurso();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnVerRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerRegistrosActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaVerRegistros();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaVerRegistros();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnVerRegistrosActionPerformed

    private void btnVerCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCursoActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaVerCurso();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaVerCurso();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnVerCursoActionPerformed

    private void btnCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaCrearCalificacion();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaCrearCalificacion();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnCalificacionActionPerformed

    private void btnVerCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCalificacionActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaVerCalificaciones();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaVerCalificaciones();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnVerCalificacionActionPerformed

    private void btnNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new VentanaIngresarNota();
            panelInterno.add(ventanaActual);
        } else {
            panelInterno.remove(ventanaActual);
            panelInterno.repaint();
            ventanaActual = new VentanaIngresarNota();
            panelInterno.add(ventanaActual);
        }
    }//GEN-LAST:event_btnNotaActionPerformed

    private void miEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEstudianteActionPerformed
        // TODO add your handling code here:
        btnEstudianteActionPerformed(evt);
    }//GEN-LAST:event_miEstudianteActionPerformed

    private void miRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroActionPerformed
        // TODO add your handling code here:
        btnRegistroActionPerformed(evt);
    }//GEN-LAST:event_miRegistroActionPerformed

    private void miVerRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerRegistroActionPerformed
        // TODO add your handling code here:
        btnVerRegistrosActionPerformed(evt);
    }//GEN-LAST:event_miVerRegistroActionPerformed

    private void miDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDocenteActionPerformed
        // TODO add your handling code here:
        btnDocenteActionPerformed(evt);
    }//GEN-LAST:event_miDocenteActionPerformed

    private void miCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalificacionActionPerformed
        // TODO add your handling code here:
        btnCalificacionActionPerformed(evt);
    }//GEN-LAST:event_miCalificacionActionPerformed

    private void miVerCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerCalificacionActionPerformed
        // TODO add your handling code here:
        btnVerCalificacionActionPerformed(evt);
    }//GEN-LAST:event_miVerCalificacionActionPerformed

    private void miNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNotaActionPerformed
        // TODO add your handling code here:
        btnNotaActionPerformed(evt);
    }//GEN-LAST:event_miNotaActionPerformed

    private void miAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAsignaturaActionPerformed
        // TODO add your handling code here:
        btnAsignaturaActionPerformed(evt);
    }//GEN-LAST:event_miAsignaturaActionPerformed

    private void miCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCursoActionPerformed
        // TODO add your handling code here:
        btnCursoActionPerformed(evt);
    }//GEN-LAST:event_miCursoActionPerformed

    private void miVerCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVerCursoActionPerformed
        // TODO add your handling code here:
        btnVerCursoActionPerformed(evt);
    }//GEN-LAST:event_miVerCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignatura;
    private javax.swing.JButton btnCalificacion;
    private javax.swing.JButton btnCurso;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVerCalificacion;
    private javax.swing.JButton btnVerCurso;
    private javax.swing.JButton btnVerRegistros;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miAsignatura;
    private javax.swing.JMenuItem miCalificacion;
    private javax.swing.JMenuItem miCurso;
    private javax.swing.JMenuItem miDocente;
    private javax.swing.JMenuItem miEstudiante;
    private javax.swing.JMenuItem miNota;
    private javax.swing.JMenuItem miRegistro;
    private javax.swing.JMenuItem miVerCalificacion;
    private javax.swing.JMenuItem miVerCurso;
    private javax.swing.JMenuItem miVerRegistro;
    private co.edu.eam.lenguaje.universidad.vistas.PanelInterno panelInterno;
    // End of variables declaration//GEN-END:variables
}
