/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.lenguaje.universidad.vistas;

import co.edu.eam.lenguaje.universidad.modelo.Asignatura;
import co.edu.eam.lenguaje.universidad.modelo.Curso;
import co.edu.eam.lenguaje.universidad.modelo.Evaluacion;
import co.edu.eam.lenguaje.universidad.modelo.Nota;
import co.edu.eam.lenguaje.universidad.modelo.Registro;
import co.edu.eam.lenguaje.universidad.modelo.Universidad;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author
 */
public class VentanaVerCalificaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaVerCalificaciones
     */
    private Universidad log;
    Asignatura buscarAsig;
    
    public VentanaVerCalificaciones() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(false);
        log = Universidad.getInstance();
    }
    
    private void limpiarCampos() {
        tfCodigoAsignatura.setText("");
        tfNombreAsignatura.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigoAsignatura = new javax.swing.JTextField();
        tfNombreAsignatura = new javax.swing.JTextField();
        cbCurso = new javax.swing.JComboBox();
        btnBuscarAsignatura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEvaluaciones = new javax.swing.JTable();

        setTitle("Ver Calificaciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/grade.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Asignatura"));

        jLabel1.setText("Código");

        jLabel2.setText("Nombre");

        jLabel3.setText("Curso");

        tfCodigoAsignatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCodigoAsignaturaKeyPressed(evt);
            }
        });

        tfNombreAsignatura.setEditable(false);

        cbCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCursoItemStateChanged(evt);
            }
        });

        btnBuscarAsignatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/buscar.png"))); // NOI18N
        btnBuscarAsignatura.setToolTipText("Buscar");
        btnBuscarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAsignaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodigoAsignatura)
                    .addComponent(tfNombreAsignatura)
                    .addComponent(cbCurso, 0, 182, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfCodigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscarAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/eam/lenguaje/universidad/imagenes/biggrade.png"))); // NOI18N

        tablaEvaluaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Nota 1", "Nota 2", "Nota n", "Definitiva"
            }
        ));
        jScrollPane1.setViewportView(tablaEvaluaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(64, 64, 64)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAsignaturaActionPerformed
        // TODO add your handling code here:
        if (tfCodigoAsignatura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el codigo de la asignatura");
            return;
        }
        buscarAsig = log.buscarAsig(tfCodigoAsignatura.getText());
        if (buscarAsig != null) {
            List<Curso> cursos = log.listarCursoAsig(buscarAsig);
            llenarComboCursos(cursos);
            tfNombreAsignatura.setText(buscarAsig.getNombre());
        } else {
            JOptionPane.showMessageDialog(null, "No se encuentra una asignatura registrado con codigo " + tfCodigoAsignatura.getText());
            limpiarCampos();
        }

    }//GEN-LAST:event_btnBuscarAsignaturaActionPerformed
    
    private void llenarComboCursos(List<Curso> cursos) {
        cbCurso.removeAllItems();
        cbCurso.addItem("Seleccione un curso");
        for (Curso curso : cursos) {
            cbCurso.addItem(curso);
        }
    }
    
    private void llenarTabla(Curso curso) {
        DefaultTableModel model = (DefaultTableModel) tablaEvaluaciones.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Cédula");
        model.addColumn("Nombre");
        for (Evaluacion eval : curso.getEvaluaciones()) {
            model.addColumn(eval);
        }
        model.addColumn("Definitiva");
        for (Registro reg : curso.getRegistros()) {
            ArrayList<String> datos = new ArrayList<>();
            datos.add(reg.getEstudiante().getDocumento());
            datos.add(reg.getEstudiante().getNombre());
            for (Evaluacion eval : curso.getEvaluaciones()) {
                Nota nota = reg.buscarNotaPorEvaluacion(eval);
                if (nota == null) {
                    datos.add("NC");
                } else {
                    datos.add(String.valueOf(nota.getNota()));
                }
            }
            datos.add(String.valueOf(reg.calcularNotaFinal()));
            model.addRow(datos.toArray());
        }
    }
    

    private void tfCodigoAsignaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodigoAsignaturaKeyPressed
        validarNumeros(evt);
    }//GEN-LAST:event_tfCodigoAsignaturaKeyPressed

    private void cbCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCursoItemStateChanged
        // TODO add your handling code here:
        if (cbCurso.getSelectedIndex() == -1 || cbCurso.getSelectedIndex() == 0) {
            return;
        }
        llenarTabla((Curso) cbCurso.getSelectedItem());
    }//GEN-LAST:event_cbCursoItemStateChanged
    
    private void validarNumeros(KeyEvent evento) {
        if (Character.isLetter((char) evento.getKeyChar())) {
            JOptionPane.showMessageDialog(null, "este campo no admite letras ");
            evento.setKeyChar((char) KeyEvent.VK_CLEAR);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAsignatura;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEvaluaciones;
    private javax.swing.JTextField tfCodigoAsignatura;
    private javax.swing.JTextField tfNombreAsignatura;
    // End of variables declaration//GEN-END:variables
}
